set(PROJECT_NAME_CMD_LINE "${PROJECT_NAME}")
set(PROJECT_VERSION_MAJOR "0")
set(PROJECT_VERSION_MINOR "1")
set(PROJECT_VERSION_PATCH "1")
set(PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")

configure_file("cmake/helpers/release.h.in" "${CMAKE_BINARY_DIR}/include/trogondb/release.h")
